#cloud-config
hostname: inode01
create_hostname_file: true
mounts:
- [ swap ]
users:
- name: ubuntu
  gecos: Ubuntu User
  shell: /bin/bash
  groups: users, admin
  sudo: ALL=(ALL) NOPASSWD:ALL
  ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvKaMHAmMHrRsmfz9yq6ax/M1qhjc+HZmUM0TmP1Ab5XPWrKcg944ZRT3S4tE93GDkC/KijsYgJgKWKPsBoJRyYODtwGTF2HNFSswcPaU9XRPDm2LaAgNLqt22oWCov8sERH4jVQnmCAqPpTc2z65qntYASG7xJFTgqlV/jiQ/bkLZd70olsg6c5n8gnuzcgz22sUJEF8prKM9xh5xI4fvJn5MCpjUd6m2rZcIedRS6ZJJmbwbFkQWUZUKDkYqsurczk5CaUug6owFP1LYckvHyP5YJ4s+gvh/JoHMX/Ouu6i5CLCUxa07tLbk5IG4k/n8eUeGGVOUBPNj3xaBYVcYKsy8puQOEW3SVUbstZ+Y7hQyTOn0wliCS2I6Xgwn1wkahtG+7bj+LVzZlretj4OrTKiGjaqaESdGtZzXwC43IpItPZRp7H6pE47HTMea4LJwRCfm5EdgXjCP983fnJ4j3mxGvlQPKA9xFfXe6YsEnARaAknLodvL6pR+x/h1r+s= posts@skillcadet
write_files:
- path: /etc/sysctl.d/kubernetes.conf
  owner: root:root
  permissions: '0644'
  content: |
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1
- path: /etc/modules-load.d/k8s.conf
  owner: root:root
  permissions: '0644'
  content: |
    overlay
    br_netfilter
runcmd:
  - [ swapoff, -a ]
  - [ modprobe, overlay ]
  - [ modprobe, br_netfilter ]
  - [ sysctl, --system ]
apt:
  sources:
    containerd.list:
      source: deb https://download.docker.com/linux/ubuntu $RELEASE stable
      keyserver: https://download.docker.com/linux/ubuntu/gpg
      keyid: 8D81803C0EBFCD88
    k8s.list:
      source: deb https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
      keyserer: https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.30/deb/Release.key
      keyid: 234654DA9A296436
packages:
  - curl
  - gnupg2
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - containerd.io
  - kubeadm
  - kubelet
  - kubectl
  - fail2ban
runcmd:
  - containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1
  - [ sed, -i, 's/SystemdCgroup \= false/SystemdCgroup \= true/g', /etc/containerd/config.toml ]
  - [ systemctl, restart, containerd ]
  - [ apt-mark, hold, kubelet, kubeadm, kubectl ]
  - [ systemctl, enable, fail2ban ]
  - [ systemctl, start, fail2ban ]
power_state:
  mode: reboot
  message: First Boot Complete
